#> This is the configuration of MyWorlds
#> For more information, you can visit the following websites:
#> https://www.spigotmc.org/resources/myworlds.8011/
#> https://www.spigotmc.org/threads/myworlds.70876/
#> entities blacklisted to be spawned
#> have these entities blacklisted to be spawned

# The interval in miliseconds a player has to wait before being teleported again
teleportInterval: 2000

# The tick interval at which time is kept locked
timeLockInterval: 20

# Whether or not world inventories are being separated using the settings
useWorldInventories: true

# Whether the player inventories are stored on the MyWorlds-configured main world
# When false, the Vanilla main world ('world') is used instead
# This option is also active when useWorldInventories is false
storeInventoryInMainWorld: false

# The main world in which new players spawn
# If left empty, the main world defined in the server.properties is used
mainWorld: lobby
useWorldEnterPermissions: false
useWorldBuildPermissions: false
useWorldUsePermissions: false
useWorldChatPermissions: false

# Whether players with the myworlds.world.keeplastpos permission are teleported to
# the last position they had on a world when using /tpp or using portals
keepLastPositionPermissionEnabled: false

# Whether players with the myworlds.world.keepinventory permission keep their inventory
# unchanged when they teleport between worlds. This disables world inventory splitting logic for them.
keepInventoryPermissionEnabled: true

# Whether portals can be replaced by other portals with the same name on the same world
allowPortalNameOverride: true

# Whether each world has it's own operator list
useWorldOperators: false

# Whether only portal blocks surrounded by obsidian can teleport players
onlyObsidianPortals: false

# Whether the world info command will calculate the world size on disk
# If this process takes too long, disable it to prevent possible server freezes
calculateWorldSize: true

# Whether all players respawn on the main world at all times
# If this should only happen when players join the server, change forceJoinOnMainWorld instead
forceMainWorldSpawn: false

# Whether all players that join the server spawn on the main world
# This includes players that joined before. Respawns are not affected.
forceJoinOnMainWorld: false

# Whether the world game mode is applied to all players, even those with the
# myworlds.world.ignoregamemode permission
forceGamemodeChanges: false

# Whether survival players instantly teleport when entering a nether portal
alwaysInstantPortal: false

# The maximum distance to look for a portal sign when entering a portal
maxPortalSignDistance: 5.0

# Turns different types of portals on or off
# When the portal is disabled, MyWorlds will not handle the portal's logic
enabledPortals:
  # Turns handling of nether portal teleportation on or off
  # Vanilla Minecraft will handle nether portals when disabled
  netherPortal: true
  # Turns handling of end portal teleportation on or off
  # Vanilla Minecraft will handle end portals when disabled
  endPortal: true
  # Enables or disables the water stream portals
  waterPortal: true
  # If water portal is enabled, true requires an exact water portal frame
  # With false, any transition air->water also detects nearby portal signs and teleports players
  waterPortalStrict: true

# Whether egg-spawned entities are allowed to spawn, even if worlds have these
ignoreEggSpawns: true

# Whether mob breeding and slime splitting is allowed to occur, even if worlds
ignoreBreedingSpawns: false

# Whether Vanilla portal physics are overrided to allow them to be built/stacked
overridePortalPhysics: true

# Whether to automatically import the world configuration of MultiVerse for new (unknown) worlds
importFromMultiVerse: true

# Whether game mode changes are logged to console, including plugin name and stack trace
# This helps to debug problems where game modes spuriously change, or fail to change properly
debugLogGMChanges: false

# Whether players are teleported to their last-known position on the world when they take a portal
# This is only active when 'remember last position' is enabled for the world
# It makes that option work not just for /tpp, but also when taking portals to a world
portalToLastPosition: true

# Whether [portal] signs can teleport non-player entities (mobs and items)
# If true, items and mobs can teleport using portals near [portal] signs
# This option can be separately set per portal using /mw setportaloption (playersonly)
portalSignsTeleportMobs: true

# Whether /world time and %myworlds_world_time% PAPI variable use 24 hours time format
# If true, shows format 23:45, if false, shows format 11:45 pm
worldTime24Hours: true

# MyWorlds caches destinations for portals frequently entered to minimize lag
# When a portal block is activated near to a previously activated one, search results are reused
# The width and height control the sensitivity of matching these results
# If a wrong portal is entered because of this, you can lower these values to fix that
portalSearchMatchRadius:
  width: 32
  height: 4
# Note that default world properties are then no longer applied, as MultiVerse takes that over
# This setting is only active if MultiVerse-Core is installed.
importFromMultiverse: ~
