world:
  loaded: true
  keepSpawnLoaded: true
  environment: normal
  chunkGenerator: ''
  gamemode: NONE
  lockedtime: 3336
  rememberlastplayerpos: false
  pvp: true
  defaultNetherPortal:
    mode: NETHER_LINK
    name: world_nether
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  defaultEndPortal:
    mode: END_PLATFORM
    name: world_the_end
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  operators: []
  deniedCreatures: []
  hunger: true
  formIce: true
  formSnow: true
  difficulty: NORMAL
  reloadWhenEmpty: false
  bedRespawnMode: ENABLED
  advancementsEnabled: true
  advancementsSilent: false
  playerLimit: -1
  playerDataFolder: ''
world_the_end:
  loaded: true
  keepSpawnLoaded: true
  environment: the_end
  chunkGenerator: ''
  gamemode: NONE
  rememberlastplayerpos: false
  pvp: true
  defaultNetherPortal:
    mode: DEFAULT
    name: ''
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  defaultEndPortal:
    mode: RESPAWN
    name: world
    display: ''
    playersOnly: true
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: true
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  operators: []
  deniedCreatures: []
  hunger: true
  formIce: true
  formSnow: true
  difficulty: NORMAL
  reloadWhenEmpty: false
  bedRespawnMode: ENABLED
  advancementsEnabled: true
  advancementsSilent: false
  playerLimit: -1
  playerDataFolder: ''
  respawn:
    type: WORLD_SPAWN
    world: world
world_nether:
  loaded: true
  keepSpawnLoaded: true
  environment: nether
  chunkGenerator: ''
  gamemode: NONE
  rememberlastplayerpos: false
  pvp: true
  defaultNetherPortal:
    mode: NETHER_LINK
    name: world
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  defaultEndPortal:
    mode: DEFAULT
    name: ''
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  operators: []
  deniedCreatures: []
  hunger: true
  formIce: true
  formSnow: true
  difficulty: NORMAL
  reloadWhenEmpty: false
  bedRespawnMode: ENABLED
  advancementsEnabled: true
  advancementsSilent: false
  playerLimit: -1
  playerDataFolder: ''
  respawn:
    type: WORLD_SPAWN
    world: world
gallery:
  loaded: true
  keepSpawnLoaded: true
  environment: flat
  chunkGenerator: ''
  gamemode: NONE
  lockedtime: 6000
  rememberlastplayerpos: false
  pvp: true
  defaultNetherPortal:
    mode: DEFAULT
    name: ''
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  defaultEndPortal:
    mode: DEFAULT
    name: ''
    display: ''
    playersOnly: false
    teleportMounts: true
    teleportToLastPosition: false
    showCredits: false
    nonPlayersCreatePortals: true
    activationEnabled: true
    autoDetect: true
  operators: []
  deniedCreatures: []
  hunger: true
  formIce: true
  formSnow: true
  difficulty: EASY
  reloadWhenEmpty: false
  bedRespawnMode: ENABLED
  advancementsEnabled: true
  advancementsSilent: false
  playerLimit: -1
  playerDataFolder: ''
